version: '3.9'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client
    ports:
      - 80:3000
    env_file:
      - .env
    networks:
      - bridge-network

networks:
  bridge-network:
    driver: bridge
